### ISSUE TITLE
Which version of Bios are you using in your build?

### ISSUE THREAD

**Issue by b0ogdan** [Coopydood/OpenCore-Z490E-CometLake#1]
Hi. Thank you very much for putting together this guide for Z490e.
I am still on Monterey since few years and i would like to update to the latest Sonoma.
I found your guide and i will follow it.
Could you please tell me which bios version are you using currently?
I am still on the oldest version 0901. I saw the latest is 3001.
Thank you again.

**Comment by Coopydood** [comment]
Hi there, thank you so much for commenting!

I just updated my BIOS from 2801 to 3001 and can confirm everything is working on macOS Sonoma 14.5. 

I'm about to release a fairly large update to this repo with some config file changes, and I'll be sure to add my BIOS version to the readme, so thanks for the idea!

**Comment by Coopydood** [comment]
Hi again, 

Just to let you know that's the repo updated with all my latest files, including my latest ``config.plist``. 
If you find yourself needing help with your adventure, please feel free to join the discord where I can help much easier: https://discord.gg/WzWkSsT

(I'd actually quite like to know how you get on as someone with the same motherboard as me!)

Kind regards

**Comment by b0ogdan** [comment]
Thank you for answering and for updating the repo so quickly!
I’m very excited to try your guide and update to Sonoma. I will join your Discord right now, and I hope we can keep in touch. It's always great to share experiences and insights, especially when we're working with the same motherboard.

**Comment by b0ogdan** [comment]
Hi.
I just got a change today to try your OC config because my hackintosh is my work computer so i had to finish some work before trying to update in case that something happens..
I could use your help a bit...first i tried just to update my current Monterey to Sonoma using your oc but without success...after the first install at the bootloader i select install Sonoma in verbose and after a ton of lines it automatically restarts..
I also made a fresh Sonoma usb and added your EFI with my current system uuid, mlb, rom, platform.
Only other changes i made was to disable and delete the 5700 xt xml and the other for to disable the nvidia card. I have a sapphire rx 580 8gb.
Also i had to disable the wifi kext sonoma because was still enabled but missing (i saw now there is a second kext called sonoma2).
After all this changes i tried to boot the usb but without luck..it just freezes at one point...Any ideas what to try?
I have not installed a fresh version in a couple of years..i was avoiding it a bit because i saw many things changed...quirks were added (which caused me trouble many times)..
The opencore validation is ok..no issues there..and the bios settings same as in your guide.
Sorry for writing you here...i joined your Discord but I`m not really sure where to write you there :sweat_smile:

**Comment by Coopydood** [comment]
No worries. 

On my discord server there is a channel near the top called ultimate-macOS-KVM, and that’s where we use to talk about all things hackintosh, or you can use one of the technology channels. Alternatively, feel free to DM me directly if you’d rather
